apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-shop-ui
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: online-shop-ui
  template:
    metadata:
      labels:
        app: online-shop-ui
    spec:
      containers:
        - name: nginx
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: ui-files
              mountPath: /usr/share/nginx/html
      volumes:
        - name: ui-files
          configMap:
            name: online-shop-ui-files
